baseURL = "http://mluther.netlify.com"
customCSS = ["", ""]
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
theme = "alpha-church"
title = "Martin Luther Evangelical Lutheran Church"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Sermons"
url = "/sermons"
weight = 2
[[menu.main]]
name = "News"
url = "/posts"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[params]
author = "Mluther"
bible_popups = true
subtitle = "10151 Sappington Rd, St Louis, MO"
title = "Martin Luther Evangelical Lutheran Church"
[params.contact]
confirm_page = "/contact_thanks"
service = "netlify"
[params.footer]
copyright = "Martin Luther Evangelical Lutheran Church @2018"
[params.landing.banner]
image = "church.png"
[[params.landing.banner.button]]
text = "Get in touch"
type = "special"
url = "/contact"
[[params.landing.banner.button]]
text = "Find out more"
url = "/about"
[params.landing.cta]
heading = "Get in touch!"
message = "We'd love to hear from you."
[params.landing.feature_icons]
enable = true
[[params.landing.feature_icons.tile]]
accent = "1"
icon = "fa-hands-helping"
icon_pack = "fas"
text = "Growing people who serve our community."
title = "Serve"
[[params.landing.feature_icons.tile]]
accent = "2"
icon = "fa-users"
icon_pack = "fas"
text = "Meeting together to hear."
title = "Meet"
[[params.landing.feature_icons.tile]]
accent = "5"
icon = "fa-comments"
icon_pack = "fas"
text = "Speaking encouragement to one-another."
title = "Speak"
[[params.landing.feature_icons.tile]]
accent = "3"
icon = "fa-heartbeat"
icon_pack = "fas"
text = "Knowing Love. Being Loved."
title = "Loved"
[params.landing.feature_images]
enable = true
[[params.landing.feature_images.tile]]
button_text = "Learn more"
image = "img/freely-10057.jpg"
text = "A church for the family."
title = "Childrens' Ministry"
url = "/kids"
[[params.landing.feature_images.tile]]
button_text = "Join a group today!"
image = "img/freely-26905.jpg"
text = "Want more during the week?"
title = "Midweek Ministries"
url = "#"
[params.landing.services]
map_location = "38.51457,-90.38086"
text = "We meet at 09:00 AM at [10151 Sappington Rd, St Louis, MO](https://www.openstreetmap.org/way/28894303#map=19/38.51476/-90.38078)."
title = "Church on Sunday"
[params.map]
latitude = "38.51465"
longitude = "-90.38083"
zoom = "18"
[params.podcast]
category = "Religion & Spirituality"
email = "test@example.com"
image = "img/podcast-cover.jpg"
sub_category = "Christianity"
subtitle = ""
summary = "Alpha-Church sermons, talks, messages—podcasted."
title = "Listen to Alpha Church"
[[params.links]]
icon = "fa-twitter"
icon_pack = "fab"
link = "https://twitter.com/MlutherMO"
service = "Twitter"
[[params.links]]
icon = "fa-facebook"
icon_pack = "fab"
link = "https://www.facebook.com/mlutherstl/"
service = "Facebook"
[[params.links]]
icon = "fa-podcast"
icon_pack = "fas"
link = "/sermons/index.xml"
service = "Podcast"
[[params.links]]
icon = "fa-rss"
icon_pack = "fas"
link = "/index.xml"
service = "Full RSS Feed"
[taxonomies]
preacher = "preachers"
series = "series"
tag = "tags"
